name: Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        type: string

      environment:
        required: true
        type: choice
        options:
          - dev
          - staging
          - production

      cluster_name:
        required: true
        type: string

      namespace:
        required: true
        type: string

      repo_name:
        required: true
        type: string

jobs:
  deploy:
    uses: Yousefa7medmaher/reusable-workflows/.github/workflows/reusbale-CD.yaml@main

    with:
      image_tag: ${{ inputs.image_tag }}
      cluster_name: ${{ inputs.cluster_name }}
      namespace: ${{ inputs.namespace }}
      repo_name: ${{ inputs.repo_name }}
      service_name: "auth-service"

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
